workflows:
  build-ios:
    name: Build iOS (Fervent)
    instance_type: mac_mini_m2
    environment:
      xcode: "15.3"
      cocoapods: default
    scripts:
      - name: Install CocoaPods (if present)
        script: |
          if [ -f Podfile ]; then
            echo "Installing pods..."
            pod install --repo-update
          else
            echo "No Podfile — skipping pods"
          fi
      - name: Build App
        script: |
          set -o pipefail
          # If you have a workspace (CocoaPods/XCFramework), use -workspace; otherwise use -project
          if [ -f FerventApp.xcworkspace ]; then
            xcodebuild -workspace FerventApp.xcworkspace -scheme FerventApp -configuration Release -derivedDataPath build ONLY_ACTIVE_ARCH=NO | xcpretty || exit $?
          else
            xcodebuild -project FerventApp.xcodeproj -scheme FerventApp -configuration Release -derivedDataPath build ONLY_ACTIVE_ARCH=NO | xcpretty || exit $?
          fi
    publishing:
      testflight:
        automatic: true
