workflows:
  ios-build:
    name: "Fervent iOS Build"
    instance_type: mac_mini_metal
    max_build_duration: 120

    environment:
      flutter: false
      xcode: "14.2"    # change to the Xcode version you want if necessary

    triggering:
      events:
        - push
        - pull_request

    scripts:
      - name: Install certificates and provisioning (handled in UI)
        script: echo "Code signing handled by Codemagic UI"

      - name: Build archive
        script: |
          set -e
          # ensure we're in the Xcode project folder if needed
          cd FerventApp || true
          xcodebuild -workspace FerventApp.xcworkspace -scheme FerventApp -configuration Release -allowProvisioningUpdates -archivePath $PWD/build/FerventApp.xcarchive archive

          # Export IPA (requires exportOptionsPlist configured in Codemagic UI or automatic signing)
          xcodebuild -exportArchive -archivePath $PWD/build/FerventApp.xcarchive -exportOptionsPlist exportOptions.plist -exportPath $PWD/build/ipa

    artifacts:
      - build/ipa/*.ipa
