workflows:
  build-ios:
    name: Build iOS (Fervent)
    instance_type: mac_mini_m2
    environment:
      xcode: latest
      cocoapods: default
      vars:
        BUNDLE_ID: "com.erioluwa.fervent"
        XCODE_SCHEME: "FerventApp"
      ios_signing:
        distribution_type: app_store
        bundle_identifier: "com.erioluwa.fervent"
    integrations:
      app_store_connect: Codemagic CI
    scripts:
      - name: Install CocoaPods (if present)
        script: |
          if [ -f Podfile ]; then
            echo "Installing pods..."
            pod install --repo-update
          else
            echo "No Podfile — skipping pods"
          fi
      - name: Build IPA for distribution
        script: |
          if [ -f FerventApp.xcworkspace ]; then
            xcode-project build-ipa --workspace "FerventApp.xcworkspace" --scheme "$XCODE_SCHEME" --export-options-plist "exportOptions.plist"
          else
            xcode-project build-ipa --project "FerventApp.xcodeproj" --scheme "$XCODE_SCHEME" --export-options-plist "exportOptions.plist"
          fi
    artifacts:
      - build/ios/ipa/*.ipa
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      app_store_connect:
        # use integration stored in Codemagic UI
        auth: integration
        # Optional: submit to TestFlight automatically
        submit_to_testflight: true
        # Optional: expire older builds in review before submitting
        expire_build_submitted_for_review: true
        # Optional: send to specific TestFlight beta groups (names exactly as in App Store Connect)
        beta_groups:
          - Internal Testers
